theme: jekyll-theme-minimal
title: Main Page
description: Can we better target who undergoes expensive PET scans?
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
